/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.eod.appconversor.view;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import pe.eod.appconversor.controller.AppController;

/**
 *
 * @author E. Oporto
 */
public class S2D extends javax.swing.JPanel {

    /**
     * Creates new form S2D
     */
    public S2D() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtSoles = new javax.swing.JTextField();
        btnConvertir = new javax.swing.JButton();

        jLabel1.setText("Ingrese monto en soles:");

        txtSoles.setText(" ");
        txtSoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSolesActionPerformed(evt);
            }
        });

        btnConvertir.setText("CONVERTIR");
        btnConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConvertir, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtSoles, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSoles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(btnConvertir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(143, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSolesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSolesActionPerformed

    private void btnConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertirActionPerformed
        // DEFINICION DE VARIABLES
        double soles, dolares;
        
        // LECTURA DE DATOS
        soles = Double.parseDouble(txtSoles.getText());
        
        // PROCESO
        AppController controlador;
        controlador = new AppController();
      
        dolares = controlador.convertirS2D(soles);
        
        // REPORTE
         double valor = 1.2345678;
        DecimalFormat df = new DecimalFormat("#.##");

        
        String reporte;
        reporte = "Monto en dólares = " + df.format(dolares);
        
        System.out.println("Monto en dólares = " + df.format(dolares));
        JOptionPane.showMessageDialog(null, reporte);
                


        // TODO add your handling code here:
    }//GEN-LAST:event_btnConvertirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConvertir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtSoles;
    // End of variables declaration//GEN-END:variables
}
