
package view;

import clases.Cambio;
import javax.swing.JOptionPane;

/**
 *
 * @author EPI
 */
public class CambioView extends javax.swing.JInternalFrame {

    /**
     * Creates new form CambioView
     */
    public CambioView() {
        initComponents();
        Cambio c= new Cambio();
        double nv=c.getTcambio();
        txttc.setText(String.valueOf(nv));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        txtCambio = new javax.swing.JTextField();
        btnCerrar = new javax.swing.JButton();
        rbADolar = new javax.swing.JRadioButton();
        rbASol = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        txtImporte = new javax.swing.JTextField();
        btnConvertir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txttc = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("CAMBIO $-S");

        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Cambio:");

        txtCambio.setEditable(false);
        txtCambio.setForeground(new java.awt.Color(255, 0, 0));

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbADolar);
        rbADolar.setSelected(true);
        rbADolar.setText("A Dolares");

        buttonGroup1.add(rbASol);
        rbASol.setText("A Soles");

        jLabel1.setText("Importe:");

        btnConvertir.setText("Cambiar");
        btnConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertirActionPerformed(evt);
            }
        });

        jLabel3.setText("Tipo de Cambio:");

        txttc.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtImporte, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnConvertir)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbADolar)
                                .addGap(18, 18, 18)
                                .addComponent(rbASol))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txttc, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel2)
                        .addGap(26, 26, 26)
                        .addComponent(txtCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCerrar)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtImporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txttc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbADolar)
                    .addComponent(rbASol))
                .addGap(18, 18, 18)
                .addComponent(btnConvertir)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCambio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCerrar)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertirActionPerformed
        // TODO add your handling code here:
        try{
            
        String sImporte=txtImporte.getText();
        double dImporte=Double.parseDouble(sImporte);
        double tc=Double.parseDouble(txttc.getText());
        Cambio c= new Cambio();
        c.setTcambio(tc);
        if (rbADolar.isSelected()){//si esta seleccionado
            double dolares=c.aDolar(dImporte);
            txtCambio.setText(String.valueOf(dolares));
        }
        if(rbASol.isSelected()){
            double sol=c.aSol(dImporte);
            txtCambio.setText(String.valueOf(sol));
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Ingrese un valor", "Java 2016", 0);
        }
        //int imp=Integer.parseInt(txtImporte.getText());

    }//GEN-LAST:event_btnConvertirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnConvertir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton rbADolar;
    private javax.swing.JRadioButton rbASol;
    private javax.swing.JTextField txtCambio;
    private javax.swing.JTextField txtImporte;
    private javax.swing.JTextField txttc;
    // End of variables declaration//GEN-END:variables
}
