/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import clases.Alumno;
import clases.Empleado;
import clases.Persona;
import javax.swing.JOptionPane;
import service.Fechas;
import java.util.*;


/**
 *
 * @author EPI
 */
public class PersonaView extends javax.swing.JInternalFrame {
    
 //public  fnac;
    /**
     * Creates new form Persona
     */
    Fechas fs,fnac;
           
    public PersonaView() {
       // Fechas fs;
           fs = new Fechas();//fecha actual
        initComponents();
        txtValor1.setVisible(false);
        txtResultado.setVisible(false);
        txtValor2.setVisible(false);
        lbDato.setVisible(false);
        lbNota1.setVisible(false);
        lbNota2.setVisible(false);
        lbResultado.setVisible(false);
        
        jLabel9.setText(fs.getFecha());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbDato = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbResultado = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtDia = new javax.swing.JTextField();
        txtMes = new javax.swing.JTextField();
        txtAnio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtValor1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        taEdad = new javax.swing.JTextArea();
        btProcesar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        cbTipo = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        txtResultado = new javax.swing.JTextField();
        txtValor2 = new javax.swing.JTextField();
        lbNota1 = new javax.swing.JLabel();
        lbNota2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("PERSONA-EMPLEADO-ALUMNO");

        jLabel1.setText("Nombres:");

        jLabel2.setText("Fecha Nacimiento:");

        lbDato.setText("Sueldo:");

        jLabel4.setText("Edad:");

        lbResultado.setText("Bonificación 12%:");

        jLabel6.setText("Dia");

        jLabel7.setText("Mes");

        jLabel8.setText("Año");

        jScrollPane1.setHorizontalScrollBar(null);

        taEdad.setColumns(20);
        taEdad.setRows(3);
        jScrollPane1.setViewportView(taEdad);

        btProcesar.setText("Procesar");
        btProcesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProcesarActionPerformed(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("jLabel9");

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione..", "Empleado", "Alumno" }));
        cbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoActionPerformed(evt);
            }
        });

        jLabel10.setText("Tipo:");

        txtResultado.setEditable(false);

        lbNota1.setText("Nota 1");

        lbNota2.setText("Nota 2");

        jLabel3.setText("Fecha actual:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel10)
                .addGap(7, 7, 7)
                .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel6)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel7)
                                .addGap(35, 35, 35)
                                .addComponent(jLabel8))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtDia, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMes, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbResultado)
                            .addComponent(jLabel4)
                            .addComponent(lbDato))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtValor1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtValor2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btProcesar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(lbNota1)
                        .addGap(53, 53, 53)
                        .addComponent(lbNota2)))
                .addGap(0, 119, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNota1)
                    .addComponent(lbNota2))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtValor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbDato))
                    .addComponent(txtValor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbResultado)
                    .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btProcesar))
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProcesarActionPerformed
       
        try {
            int dia = Integer.parseInt(txtDia.getText());
            int mes = Integer.parseInt(txtMes.getText());
            int anio = Integer.parseInt(txtAnio.getText());

            //Fechas fnac;
            fnac = new Fechas(dia, mes, anio);//fecha nacimiento

            Persona per;
            per = new Persona();
            per.setFechaNac(fnac);
            per.setNombres(txtNombre.getText());
            int iValor = cbTipo.getSelectedIndex();
            switch (iValor) {
                default:
                    //JOptionPane.showMessageDialog(null, "I1 ", "UNI", 1);   
                    break;
                case 1:
                    try {
                        Empleado e;
                        e = new Empleado();
                        e.setSueldo(Double.parseDouble(txtValor1.getText()));
                        txtResultado.setText(String.valueOf(e.bonificacion()));
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, "Ingrese el Sueldo", "UNI", 0);
                    }
                    break;
                case 2:
                    try {
                        Alumno al;
                        al = new Alumno();
                        al.setNota1(Integer.parseInt(txtValor1.getText()));
                        al.setNota2(Integer.parseInt(txtValor2.getText()));
                        txtResultado.setText(String.valueOf(al.promedio()));
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, "Ingrese las Notas", "UNI", 0);
                    }
//JOptionPane.showMessageDialog(null, "Seleccion3", "UNI", 1);
                    break;
            }
            Empleado emp;
            emp = new Empleado();

            if (fs.validafecha() && fnac.validafecha()) {
                //jLabel9.setText(per.getEstado());
                
                taEdad.setText(fs.calcularFechas(fnac));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ingrese Fecha de Nacimiento", "UNI", 0);
    }//GEN-LAST:event_btProcesarActionPerformed
    }//fin boton
    private void cbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoActionPerformed
        int iValor = cbTipo.getSelectedIndex();
        switch (iValor) {
            default:
                txtValor1.setVisible(false);
                txtResultado.setVisible(false);
                txtValor2.setVisible(false);
                lbDato.setVisible(false);
                lbNota1.setVisible(false);
                lbNota2.setVisible(false);
                lbResultado.setVisible(false);

                break;
            case 1:
                lbDato.setText("Sueldo:");
                lbResultado.setText("Bonificación 12%:");
                lbResultado.setVisible(true);
                txtValor1.setText(null);
                txtResultado.setText(null);
                txtValor1.setVisible(true);
                txtResultado.setVisible(true);
                lbDato.setVisible(true);
                lbResultado.setVisible(true);

                txtValor2.setVisible(false);
                lbNota1.setVisible(false);
                lbNota2.setVisible(false);

                break;
            case 2:
                lbDato.setText("Notas:");
                lbResultado.setText("Promedio:");
                lbResultado.setVisible(true);
                txtValor1.setText(null);
                txtResultado.setText(null);
                txtValor1.setVisible(true);
                txtResultado.setVisible(true);
                lbDato.setVisible(true);
                lbResultado.setVisible(true);

                txtValor2.setVisible(true);
                lbNota1.setVisible(true);
                lbNota2.setVisible(true);
                txtValor2.setText(null);
                break;
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btProcesar;
    private javax.swing.JComboBox cbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbDato;
    private javax.swing.JLabel lbNota1;
    private javax.swing.JLabel lbNota2;
    private javax.swing.JLabel lbResultado;
    private javax.swing.JTextArea taEdad;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtDia;
    private javax.swing.JTextField txtMes;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtResultado;
    private javax.swing.JTextField txtValor1;
    private javax.swing.JTextField txtValor2;
    // End of variables declaration//GEN-END:variables
}
