/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pe.ccs.app.view;

import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import pe.ccs.app.model.Libro;
import pe.ccs.app.model.Pedido;
import pe.ccs.app.service.Metodos;

/**
 *
 * @author c.carranza.solis
 */
public class Libreria extends javax.swing.JFrame {
  

    /**
     * Creates new form Libreria
     */
    public Libreria() {
        initComponents();
        btnCboBox1.setSelectedIndex(-1);
       txtPrecio.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tarjeta = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        btnCboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnCboBox2 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEjemplares = new javax.swing.JTextField();
        btnProcesar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        MasterCard = new javax.swing.JRadioButton();
        AmericanExpress = new javax.swing.JRadioButton();
        VISA = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Libro");

        btnCboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "García Marquez", "Bryce Echenique", "Vargas Llosa", " " }));
        btnCboBox1.setSelectedIndex(-1);
        btnCboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Autor");

        jLabel3.setText("Ficha");

        btnCboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCboBox2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Precio");

        txtPrecio.setEnabled(false);
        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });
        txtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPrecioKeyPressed(evt);
            }
        });

        jLabel5.setText("Cantidad de Ejemplares:");

        txtEjemplares.setEnabled(false);

        btnProcesar.setText("Procesar");
        btnProcesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcesarActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jLabel6.setText("Nombre:");

        jLabel7.setText("Direccion");

        jLabel8.setText("Email:");

        tarjeta.add(MasterCard);
        MasterCard.setText("Mastercard");
        MasterCard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MasterCardMouseClicked(evt);
            }
        });

        tarjeta.add(AmericanExpress);
        AmericanExpress.setText("American Express");
        AmericanExpress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AmericanExpressMouseClicked(evt);
            }
        });

        tarjeta.add(VISA);
        VISA.setText("VISA");
        VISA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VISAMouseClicked(evt);
            }
        });

        jLabel9.setText("Número de Tarjeta");

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnProcesar)
                                .addGap(67, 67, 67)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtEjemplares, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(141, 141, 141)
                                        .addComponent(jButton1))
                                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnCboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)))
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel1)
                                                .addComponent(jLabel8)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(27, 27, 27)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtNombre)
                                                    .addComponent(txtDireccion)
                                                    .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(98, 98, 98)
                                                .addComponent(jLabel2))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(MasterCard)
                                        .addGap(18, 18, 18)
                                        .addComponent(AmericanExpress)
                                        .addGap(29, 29, 29)
                                        .addComponent(VISA))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(29, 29, 29)
                                        .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnCboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MasterCard)
                    .addComponent(AmericanExpress)
                    .addComponent(VISA))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtEjemplares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(52, 52, 52))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(42, 42, 42)))
                        .addComponent(jLabel3))
                    .addComponent(btnProcesar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   public void borrar(){
         btnCboBox2.setEnabled(true);
         btnCboBox2.removeAllItems();
         
   }
   
   public void seleccionar(){
       
String [] librosGarcia={"Cien Años de Soledad","Crónica de una muerte anunciada","El amor en los tiempos del cólera"};
String [] librosBryce={"Un mundo para Julius","El Huerto de mi amada","No me esperen en Abril"};
String [] librosVargas={"La ciudad y los perros","La casa verde","La tia Julia y el escribidor"};
       
       
         if(btnCboBox1.getSelectedIndex()==-1){
            btnCboBox2.removeAllItems();
            btnCboBox2.setEnabled(false);
            
     }
      if(btnCboBox1.getSelectedIndex()==0){
            borrar(); 
            for(int i=0;i<librosGarcia.length;i++){
            btnCboBox2.addItem(librosGarcia[i]);
            }
         btnCboBox2.setSelectedIndex(-1);       
     }
     if(btnCboBox1.getSelectedIndex()==1){
             borrar();  
        
          for(int i=0;i<librosBryce.length;i++){
            btnCboBox2.addItem(librosBryce[i]);
         }
        btnCboBox2.setSelectedIndex(-1);
         
              
     }
     if(btnCboBox1.getSelectedIndex()==2){
              borrar();       
       for(int i=0;i<librosVargas.length;i++){
            btnCboBox2.addItem(librosVargas[i]);
         }
         btnCboBox2.setSelectedIndex(-1);
              
     }
   }
    private void btnCboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCboBox1ActionPerformed
      seleccionar();      
    }//GEN-LAST:event_btnCboBox1ActionPerformed

    private void btnCboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCboBox2ActionPerformed
        if(btnCboBox2.getSelectedIndex()==-1){
              txtPrecio.setEnabled(false);
              txtEjemplares.setEnabled(false);
              txtPrecio.setText("");
              txtEjemplares.setText("");
              
        }else
        {
            txtPrecio.setEnabled(true);
            txtPrecio.requestFocus();
        }
    }//GEN-LAST:event_btnCboBox2ActionPerformed

    private void txtPrecioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioKeyPressed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        evt.setSource((char)KeyEvent.VK_CLEAR);
        txtEjemplares.setEnabled(true);
        txtEjemplares.requestFocus();
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void btnProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcesarActionPerformed
        
      Libro libro = new Libro();
        Pedido pedido= new Pedido();
       
        try {
           
        
        libro.setPrecio(Double.parseDouble(txtPrecio.getText()));
        libro.setCantidad_libros(Double.parseDouble(txtEjemplares.getText()));
        
        pedido.setNombre(txtNombre.getText());
        pedido.setDireccion(txtDireccion.getText());
        pedido.setEmail(txtEmail.getText());
        pedido.setNum_de_tarjeta(txtNumero.getText());
        
        Metodos metodos;
        metodos = new Metodos();
        metodos.procesar(libro);
       
       
       jTextArea1.append("Cliente: "+txtNombre.getText()); 
       jTextArea1.append(System.getProperty("line.separator"));
       jTextArea1.append("Direccion: "+txtDireccion.getText()); 
       jTextArea1.append(System.getProperty("line.separator"));
       jTextArea1.append("Email: "+txtEmail.getText()); 
       jTextArea1.append(System.getProperty("line.separator"));
       jTextArea1.append("Numero de Tarjeta: "+txtNumero.getText()); 
       jTextArea1.append(System.getProperty("line.separator"));
       
       jTextArea1.append("Nombre del autor: "+btnCboBox1.getSelectedItem()); 
       jTextArea1.append(System.getProperty("line.separator"));
       jTextArea1.append("Nombre del libro: "+btnCboBox2.getSelectedItem()); 
       jTextArea1.append(System.getProperty("line.separator"));
       jTextArea1.append("Precio del libro: "+txtPrecio.getText()); 
       jTextArea1.append(System.getProperty("line.separator")); // Esto para el salto de línea 
       jTextArea1.append("Cantidad de Ejemplares: "+txtEjemplares.getText()); 
       jTextArea1.append(System.getProperty("line.separator")); // Esto para el salto de línea 
       jTextArea1.append("Cantidad Total a Pagar: "+libro.getTotal()); 
       jTextArea1.append(System.getProperty("line.separator"));
            
            
        } catch (Exception e) {
            
            String msg = "Error en el proceso.";
      if(e.getMessage() != null){
        msg += "\n" + e.getMessage();
      }
      JOptionPane.showMessageDialog(rootPane, msg, "ERROR", JOptionPane.ERROR_MESSAGE);
            
        }
       

    /* 
       
        
         String repo = "";
    repo += "Precio: " + libro.getPrecio() + "\n";
    repo += "Cantidad de ejemplares: " + libro.getCantidad_libros() + "\n";
     repo += "Total de venta: " + libro.getTotal() + "\n";
    
    JOptionPane.showMessageDialog(rootPane, repo);
 */
       
       
       
       
       
       
       
       
       
       
 
    }//GEN-LAST:event_btnProcesarActionPerformed

    private void MasterCardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MasterCardMouseClicked
        // TODO add your handling code here:
        Pedido pedido= new Pedido();
        pedido.setTipo_de_tarjeta(MasterCard.getLabel());
    }//GEN-LAST:event_MasterCardMouseClicked

    private void AmericanExpressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AmericanExpressMouseClicked
        // TODO add your handling code here:
        Pedido pedido= new Pedido();
         pedido.setTipo_de_tarjeta(AmericanExpress.getLabel());
    }//GEN-LAST:event_AmericanExpressMouseClicked

    private void VISAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VISAMouseClicked
        // TODO add your handling code here:
          Pedido pedido= new Pedido();
         pedido.setTipo_de_tarjeta(VISA.getLabel());
    }//GEN-LAST:event_VISAMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Libreria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Libreria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Libreria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Libreria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Libreria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JRadioButton AmericanExpress;
    public static javax.swing.JRadioButton MasterCard;
    public static javax.swing.JRadioButton VISA;
    private javax.swing.JComboBox btnCboBox1;
    private javax.swing.JComboBox btnCboBox2;
    private javax.swing.JButton btnProcesar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.ButtonGroup tarjeta;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEjemplares;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
